      SUBROUTINE SELFS(I,J,R2,IOVPAR,EM,NE)
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION PARM(13),EM(NE,1)
      EXTERNAL IOVPAR
C
      ID=IOVPAR(I,J,R2,PARM)
      EM(1,1)=PARM(13)
      RETURN
      END
