      SUBROUTINE SELFP(I,J,R2,IOVPAR,EM,NE)
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION PARM(13),EM(NE,3)
      EXTERNAL IOVPAR
C
      ID=IOVPAR(I,J,R2,PARM)
      DO 11 L=1,3
      DO 10 M=1,3
10    EM(L,M)=0.0D0
11    EM(L,L)=PARM(12)
      RETURN
      END
