      SUBROUTINE SKSS(X,X2,I,J,R2,IOVPAR,EM,NE)
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION X(6),X2(6),PARM(13),EM(1,1)
      EXTERNAL IOVPAR
C
      ID=IOVPAR(I,J,R2,PARM)
      EM(1,1)=PARM(10)
      RETURN
      END
